name: Deploy HomeVault.Web to Azure

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy static site to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: homevault-webapp
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE }}
          package: .
